version: '2.1'
services:
  taky-db:
    container_name: taky-db
    image: mariadb
    ports: 
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=mypass
      - MARIADB_DATABASE=TAKYCoT
    restart: unless-stopped