apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: taky-db:3306
    database: TAKYCoT
    user: grafana
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: 9AUZaNACtnc2TFcDups8euUy